# Generated by Django 5.2.6 on 2025-10-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0004_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
