# Generated by Django 5.2.5 on 2025-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0005_order_district_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
