# Generated by Django 5.2.5 on 2025-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0006_alter_plant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_guide',
            field=models.TextField(blank=True, help_text='General care instructions for the plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='common_problems',
            field=models.TextField(blank=True, help_text='Common issues and solutions'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer_needs',
            field=models.CharField(blank=True, help_text='Fertilizer recommendations', max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity_level',
            field=models.CharField(blank=True, help_text='Preferred humidity level', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Recommended soil type', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_needs',
            field=models.CharField(blank=True, help_text='Amount of sunlight needed', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature_range',
            field=models.CharField(blank=True, help_text='Ideal temperature range', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_schedule',
            field=models.CharField(blank=True, help_text='How often to water the plant', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
