# Generated by Django 5.2.5 on 2025-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0007_plant_care_guide_plant_common_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_guide',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='common_problems',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fertilizer_needs',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='humidity_level',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='sunlight_needs',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='temperature_range',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='watering_schedule',
        ),
        migrations.AddField(
            model_name='plant',
            name='wiki_link',
            field=models.URLField(blank=True, help_text='Optional: link to more info about the plant', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
