# Generated by Django 5.2.6 on 2025-11-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0008_remove_plant_care_guide_remove_plant_common_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='nursery_app.order'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
