# Generated by Django 5.2.6 on 2025-11-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0009_plant_order_plant_plants_plant_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='order',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nursery_app.order')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='nursery_app.plant')),
            ],
        ),
    ]
